source "https://rubygems.org"

gem "fastlane"
gem "fastlane-plugin-flutter_version", git: "https://github.com/tianhaoz95/fastlane-plugin-flutter-version"

# gem "fastlane-plugin-flutter_version", path: "/Volumes/Apps/untitled-folder/fastlane-plugin-flutter-version"
